export const categories = [
  {
    id: 'bearings',
    name: '轴承',
    en: 'BEARINGS',
    image: 'bearing',
    description: '深沟球轴承 · 推力轴承',
  },
  {
    id: 'fasteners',
    name: '紧固件',
    en: 'FASTENERS',
    image: 'bolt',
    description: '螺钉 · 螺母 · 垫圈',
  },
  {
    id: 'transmission',
    name: '传动配件',
    en: 'TRANSMISSION',
    image: 'coupling',
    description: '联轴器 · 同步带轮',
  },
];
export type Product = {
  id: string;
  name: string;
  category: string;
  type: string;
  material: string;
  size: string;
  spec: string;
  image: string;
  note: string;
};
export const products: Product[] = [
  {
    id: 'DEMO-B01',
    name: '深沟球轴承',
    category: 'bearings',
    type: '深沟球轴承',
    material: '轴承钢',
    size: '20',
    spec: '内径 20 mm · 外径 47 mm',
    image: 'bearing',
    note: '通用旋转支撑的选型示意',
  },
  {
    id: 'DEMO-B02',
    name: '深沟球轴承',
    category: 'bearings',
    type: '深沟球轴承',
    material: '不锈钢',
    size: '20',
    spec: '内径 20 mm · 外径 47 mm',
    image: 'bearing',
    note: '不同材质的选型信息对比',
  },
  {
    id: 'DEMO-B03',
    name: '深沟球轴承',
    category: 'bearings',
    type: '深沟球轴承',
    material: '轴承钢',
    size: '10',
    spec: '内径 10 mm · 外径 30 mm',
    image: 'bearing',
    note: '小尺寸部件的目录示意',
  },
  {
    id: 'DEMO-B04',
    name: '推力轴承',
    category: 'bearings',
    type: '推力轴承',
    material: '轴承钢',
    size: '30',
    spec: '内径 30 mm · 外径 52 mm',
    image: 'thrust',
    note: '轴向支撑的品类示意',
  },
  {
    id: 'DEMO-F01',
    name: '内六角螺钉',
    category: 'fasteners',
    type: '螺钉',
    material: '不锈钢',
    size: 'M6',
    spec: 'M6 × 20 mm · 内六角',
    image: 'bolt',
    note: '装配紧固件的规格展示',
  },
  {
    id: 'DEMO-F02',
    name: '六角螺母',
    category: 'fasteners',
    type: '螺母',
    material: '不锈钢',
    size: 'M8',
    spec: 'M8 · 六角结构',
    image: 'nut',
    note: '配套螺母的目录示意',
  },
  {
    id: 'DEMO-F03',
    name: '平垫圈',
    category: 'fasteners',
    type: '垫圈',
    material: '不锈钢',
    size: 'M8',
    spec: 'M8 · 平面垫圈',
    image: 'washer',
    note: '连接辅件的目录示意',
  },
  {
    id: 'DEMO-F04',
    name: '内六角螺钉',
    category: 'fasteners',
    type: '螺钉',
    material: '碳钢',
    size: 'M8',
    spec: 'M8 × 25 mm · 内六角',
    image: 'bolt',
    note: '材质与规格筛选示意',
  },
  {
    id: 'DEMO-T01',
    name: '弹性联轴器',
    category: 'transmission',
    type: '联轴器',
    material: '铝合金',
    size: '20',
    spec: '轴孔 20 mm · 弹性连接',
    image: 'coupling',
    note: '传动连接的选型示意',
  },
  {
    id: 'DEMO-T02',
    name: '弹性联轴器',
    category: 'transmission',
    type: '联轴器',
    material: '铝合金',
    size: '10',
    spec: '轴孔 10 mm · 弹性连接',
    image: 'coupling',
    note: '小型轴系的目录示意',
  },
  {
    id: 'DEMO-T03',
    name: '弹性联轴器',
    category: 'transmission',
    type: '联轴器',
    material: '铝合金',
    size: '30',
    spec: '轴孔 30 mm · 弹性连接',
    image: 'coupling',
    note: '不同轴孔尺寸的展示',
  },
  {
    id: 'DEMO-T04',
    name: '同步带轮',
    category: 'transmission',
    type: '带轮',
    material: '铝合金',
    size: '20',
    spec: '轴孔 20 mm · 齿形结构',
    image: 'pulley',
    note: '同步传动的品类示意',
  },
];
